Release 1.56.0 (#3664)
* Update gutenberg reference

* Update package-lock

* Update gutenberg ref

* Updated gutenberg ref

* Updating gutenberg ref

* Updated hermes executable to hermesc for building bundle

* Updated bundle

* Update gutenberg ref

* Add changes to package-lock.json after running npm install

* Disabled npm cache on CI

* Update gutenberg ref

* Add @react-native to transformIgnorePatterns in jest config

Expecting this to fix the following error:
```
/home/circleci/project/gutenberg/node_modules/@react-native/polyfills/error-guard.js:14
type ErrorHandler = (error: mixed, isFatal: boolean) => void;
        ^^^^^^^^^^^^

SyntaxError: Unexpected identifier

    at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
    at Object.<anonymous> (gutenberg/node_modules/react-native/jest/setup.js:434:6)
```

* Update gutenberg ref

* Update gutenberg ref

* updated gutenberg ref

* Upgrade react-native related devDependencies

* Update gutenberg ref

* Fix check correctness diff error

* Update gutenberg ref

* Update gutenberg ref

* Updated bundle files

* Updated gutenberg ref

* Updated gutenberg ref

* Updated gutenberg ref

* Adding cache-version file for re-running circle-ci

* Update gutenberg ref

* Updated gutenberg ref

* Updated ref, removed react-native-mirror s3 from bridge gradle

* updated bundle

* Update podspecs by running generate-podspecs.sh script

* Updating gutenberg ref

* Update bundle

* Update gutenberg ref

* Revert "Disabled npm cache on CI"

This reverts commit 3958c64335bc1116751d8c016c28fa667a6f7a27.

* Modify generate-podspecs.sh script to run FBReactNativeSpec codegen ahead of time

* Update gutenberg ref

* Update package-lock.json

* Update package-lock.json

* Add workaround for FBReactNativeSpec podspec in generate-poscpecs.sh script

* Update commit hash of FBReactNativeSpec

* Fix typo

* Update commit hash of FBReactNativeSpec

* Add missing external podspecs to generate-podspecs.sh script

* Re-generate third-party-podspecs, remove react-native-linear-gradient podspec

* Update commit hash of FBReactNativeSpec

* Add exception for react-native-slider fork

* Remove tag from react-native-slider podspec

* Fix react-native-slider git source

* Update gutenberg ref

* Update bundles

* Update gutenberg reference

* Update release notes with fix for Gboard enter detection

* Update gutenberg ref

* Update jetpack ref

* Update bundles

* Update gutenberg ref

* Update gutenberg ref

* Re-run generate-podspecs.sh to update BVLinearGradient podspec

* Update gutenberg ref

* Update bundles

* Shallow clone project for CI tasks

Decrease CI task duration by reducing depth of git operations.

- [CircleCI: Shallow Repository Cloning](https://support.circleci.com/hc/en-us/articles/360045096514-Shallow-Repository-Cloning)
- [CircleCI: How do I modify the checkout step?](https://support.circleci.com/hc/en-us/articles/115015659247-How-do-I-modify-the-checkout-step-)
- [Example: CircleCI Shallow Clone](https://discuss.circleci.com/t/shallow-clone-for-circleci-2-0-builds/20200)

* Update Gutenberg ref

* Updates gutenberg reference

* Update Gutenberg submodule ref

Fix component inspector error in React Native

* Bump Gutenberg to latest trunk

* Update gutenberg ref

* Changes to package-lock.json after running npm install

* Update bundles

* Run ./bin/generate-podspecs.sh

* Update gutenberg ref to merge commit

* Update Gutenberg ref

* Add a few improvements and checks to generate-podspecs.sh

* Add a warning field at the bottom of all podspecs

* Add a warning when the tag or commit field is missing in a podspec

* Patch react-native-blur.podspec adding the missing tag

* Better wording

* Update bundles

* Update FBReactNativeSpec ref

* Indent patch messages

* Patch react-native-blur.podspec again as 3.6.0 tag is missing

* CI fetches commit reference directly

The CI configuration is set to clone with a depth of 1. If the CI tasks
then attempts to reference an older commit in the relevant branch, an
error occurs. This might occur when a branch merge occurs between a CI
tasks beginning and the point it attempt to fetch the HEAD of the
branch. This change configures the shallow clone to fetch the specific
commit reference, rather than the HEAD of the relevant branch.

* Update gutenberg reference

* Update gutenberg ref

* Update gutenberg ref

* Update gutenberg ref

* Update gutenberg ref

* Update bundles

* Generate build

* Moved item to the unreleased section of release notes

* Update Gutenberg ref with merge commit

* Bump Gutenberg hash

* Update Gutenberg hash

* Bump Gutenberg hash

* Update Gutenberg hash

* Update Gutenberg hash

* Temporary Metro patch until RN upgrades Metro

Issue message: "Error: EISDIR: illegal operation on a directory, read"
Fix PR on Metro: https://github.com/facebook/metro/pull/567

* Bump Gutenberg hash

* Bump Gutenberg to the merged hash

* Update Gutenberg ref

* Update release notes

* Fix incorrect block insertion point after blurring post title

Selecting the title selection status within the same `useSelect` for
reusable blocks caused the title selection status to become stale, due
to the dependency array for the `useSelect` hook.

The staleness caused the block insertion point to show up in the
incorrect location after blurring the title text input.

* Update gutenberg ref

* Bump Gutenberg

* Update RELEASE-NOTES.txt

* Update Gutenberg hash which contains fix to Android artifact publishing

* Bump Gutenberg

* Add: Grid block, from block-experiments repo

* Bump block-expeiments

* Update the no_output_timeout to 15min

* Revert the longer timeout.

* Add block-experiments to eslintignore

* Remove comment.

* Fix prettier

* Bump block-experiements

* All Layout Grid controls

* Bump block experiment fixes

* Fix up the block setup code

* Fix the availability

* Update bundle

* Simplify the layout grid block registration.

* Update the bundle js files

* Fix minor prettier issue.

* Bump map since it changed

* bump the latest version of Gutenberg

* Update the bundle

* Update gutenberg ref

* Generate bundle

* Bump Gutenberg

* Update Gutenberg ref

* Update gutenberg ref

* Install latest packages

* Install latest packages

* Remove duplicative release note

* Bump Gutenberg

* Update extra node modules resolver

Gutenberg mobile dependencies were resolved using the Jetpack path, so now we check first if the module exists in the Jetpack submodule before solving it with that path.

* Remove email-validator dependency

This dependency is already defined in Jetpack submodule and it's only used there.

* Remove yarn.lock file

* Remove yarn dependency

* Clarify comment in extra node modules resolver

* Update Gutenberg ref with merge commit

* Bump Gutenberg

* Release script: Update gb mobile version to 1.56.0

* Release script: Update gutenberg ref

* Release script: Update bundle for: 1.56.0

* Update Release notes

Co-authored-by: Cameron Voell <cameronvoell@gmail.com>
Co-authored-by: Ceyhun Ozugur <ceyhunozugur@gmail.com>
Co-authored-by: Amanda Riu <amanda.riu@automattic.com>
Co-authored-by: David Calhoun <438664+dcalhoun@users.noreply.github.com>
Co-authored-by: Carlos Garcia <fluiddot@gmail.com>
Co-authored-by: Antonis Lilis <antonis.lilis@automattic.com>
Co-authored-by: Paul Von Schrottky <paul.von.schrottky@automattic.com>
Co-authored-by: Enej Bajgoric <enej.bajgoric@automattic.com>
Co-authored-by: AmandaRiu <5810477+AmandaRiu@users.noreply.github.com>
Co-authored-by: Stefanos Togkoulidis <stefanostogoulidis@gmail.com>
Co-authored-by: Siobhan <siobhan@automattic.com>
Co-authored-by: Oguz Kocer <oguz.kocer@automattic.com>
Co-authored-by: Oguz Kocer <oguzkocer@users.noreply.github.com>
Co-authored-by: Siobhan Bamber <SiobhyB@users.noreply.github.com>