Update jest and jest-snapshot packages
The outdated packages resulted in the following CI failure.

```
TypeError: snapshotResolver.resolveSnapshotPath is not a function

  at Object._default [as default] (node_modules/jest-jasmine2/build/setup_jest_globals.js:101:41)
```

These updates were completed to resolve the error and mirror updates
within the `gutenberg` submodule, which updated `jest-snapshot`:
https://github.com/WordPress/gutenberg/pull/37396

The cause of the error is a breaking change that landed in
`jest-snapshots@27`: https://github.com/facebook/jest/pull/8829