Use static linkage
This resolved the build error we were seeing before:

```
Undefined symbols for architecture arm64
"facebook::react::NativeVibrationSpecJSI::NativeVibrationSpecJSI(facebook::react::ObjCTurboModule::InitParams const&)", referenced from:
```

However, the framework is still not building successfully. Below are the
new errors. They seem related to access control and missing imports,
which make me hopeful I'll be able to address them easily.

```
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/SourceFile.swift:36:66: cannot find type 'WKUserScript' in scope
    public func jsScript(with argument: String? = nil) throws -> WKUserScript {
                                                                 ^~~~~~~~~~~~
⚠️  /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/GutenbergBridgeDataSource.swift:3:44: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
public protocol GutenbergBridgeDataSource: class {
                                           ^~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:7:44: cannot find type 'RCTEventEmitter' in scope
public class RNReactNativeGutenbergBridge: RCTEventEmitter {
                                           ^~~~~~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/GutenbergBridgeDelegate.swift:131:11: cannot find type 'RCTLogLevel' in scope
extension RCTLogLevel {
          ^~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/GutenbergBridgeDelegate.swift:117:25: cannot find type 'RCTLogLevel' in scope
    init (_ rnLogLevel: RCTLogLevel) {
                        ^~~~~~~~~~~
⚠️  /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/GutenbergBridgeDelegate.swift:143:42: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
public protocol GutenbergBridgeDelegate: class {
                                         ^~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:14:21: initializer does not override a designated initializer from its superclass
    public override init() {
           ~~~~~~~~ ^
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:33:118: cannot find type 'RCTResponseSenderBlock' in scope
    func requestMediaPickFrom(_ source: String, filter: [String]?, allowMultipleSelection: Bool, callback: @escaping RCTResponseSenderBlock) {
                                                                                                                     ^~~~~~~~~~~~~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:71:72: cannot find type 'RCTResponseSenderBlock' in scope
    func getOtherMediaOptions(_ filter: [String]?, callback: @escaping RCTResponseSenderBlock) {
                                                                       ^~~~~~~~~~~~~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:86:70: cannot find type 'RCTResponseSenderBlock' in scope
    func requestMediaImport(_ urlString: String, callback: @escaping RCTResponseSenderBlock) {
                                                                     ^~~~~~~~~~~~~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:191:70: cannot find type 'RCTResponseSenderBlock' in scope
    func requestMediaEditor(_ urlString: String, callback: @escaping RCTResponseSenderBlock) {
                                                                     ^~~~~~~~~~~~~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:224:26: method does not override any method from its superclass
    public override func sendEvent(withName name: String, body: Any?) {
           ~~~~~~~~      ^
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:247:59: cannot find type 'RCTPromiseResolveBlock' in scope
    func fetchRequest(_ path: String, resolver: @escaping RCTPromiseResolveBlock, rejecter: @escaping RCTPromiseRejectBlock) {
                                                          ^~~~~~~~~~~~~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:247:103: cannot find type 'RCTPromiseRejectBlock' in scope
    func fetchRequest(_ path: String, resolver: @escaping RCTPromiseResolveBlock, rejecter: @escaping RCTPromiseRejectBlock) {
                                                                                                      ^~~~~~~~~~~~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:259:86: cannot find type 'RCTPromiseResolveBlock' in scope
    func postRequest(_ path: String, data: [String: AnyObject]?, resolver: @escaping RCTPromiseResolveBlock, rejecter: @escaping RCTPromiseRejectBlock) {
                                                                                     ^~~~~~~~~~~~~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:259:130: cannot find type 'RCTPromiseRejectBlock' in scope
    func postRequest(_ path: String, data: [String: AnyObject]?, resolver: @escaping RCTPromiseResolveBlock, rejecter: @escaping RCTPromiseRejectBlock) {
                                                                                                                                 ^~~~~~~~~~~~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:283:52: cannot find type 'RCTPromiseResolveBlock' in scope
    func showUserSuggestions(_ resolver: @escaping RCTPromiseResolveBlock, rejecter: @escaping RCTPromiseRejectBlock) {
                                                   ^~~~~~~~~~~~~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:283:96: cannot find type 'RCTPromiseRejectBlock' in scope
    func showUserSuggestions(_ resolver: @escaping RCTPromiseResolveBlock, rejecter: @escaping RCTPromiseRejectBlock) {
                                                                                               ^~~~~~~~~~~~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:295:50: cannot find type 'RCTPromiseResolveBlock' in scope
        func showXpostSuggestions(_ resolver: @escaping RCTPromiseResolveBlock, rejecter: @escaping RCTPromiseRejectBlock) {
                                                        ^~~~~~~~~~~~~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:295:94: cannot find type 'RCTPromiseRejectBlock' in scope
        func showXpostSuggestions(_ resolver: @escaping RCTPromiseResolveBlock, rejecter: @escaping RCTPromiseRejectBlock) {
                                                                                                    ^~~~~~~~~~~~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:344:68: cannot find type 'RCTResponseSenderBlock' in scope
    func requestFocalPointPickerTooltipShown(_ callback: @escaping RCTResponseSenderBlock) {
                                                                   ^~~~~~~~~~~~~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:380:60: cannot find type 'RCTResponseSenderBlock' in scope
    func requestBlockTypeImpressions(_ callback: @escaping RCTResponseSenderBlock) {
                                                           ^~~~~~~~~~~~~~~~~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:6:2: only classes that inherit from NSObject can be declared @objc
@objc (RNReactNativeGutenbergBridge)
~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
⚠️  /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:417:5: 'public' modifier is redundant for enum declared in a public extension
    public enum ActionButtonType: String {
    ^~~~~~~
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:440:26: method does not override any method from its superclass
    public override func supportedEvents() -> [String]! {
           ~~~~~~~~      ^
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:444:33: method does not override any method from its superclass
    public override static func requiresMainQueueSetup() -> Bool {
           ~~~~~~~~             ^
❌ /Users/gio/Developer/a8c/gutenberg-mobile/gutenberg/packages/react-native-bridge/ios/RNReactNativeGutenbergBridge.swift:448:26: method does not override any method from its superclass
    public override func batchDidComplete() {
           ~~~~~~~~      ^
```