Reorder of moduleDirectories Jest configuration
The Jest test runner found was resolving different version of Jest
sub-dependencies, which resulted in the following error.

```
TypeError: snapshotResolver.resolveSnapshotPath is not a function

  at Object._default [as default] (node_modules/jest-jasmine2/build/setup_jest_globals.js:101:41)
```

Specifically, the test runner resolved
`node_modules/jest-jasmine2@26.6.3 >
gutenberg/node_modules/jest-snapshot@27.4.5`. `jest-snapshot@27`
includes a breaking change of a newly returned `Promise`:

https://github.com/facebook/jest/pull/8829

This reordering prioritizes the dependencies found in the top-level
`node_modules` directory over the directory found within the `gutenberg`
submodule.