build: Only update xcframework Podfile.lock with valid targets
We are required to run `bin/generate-podspecs.sh` twice to capture the
correct target. This change ensures the xcframework is only updated on
the second run with the correct target, otherwise the following error
occurs:

```
Installing FBReactNativeSpec 0.69.4

[!] Error installing FBReactNativeSpec
[!] /opt/homebrew/bin/git -C /var/folders/c5/mkbb257d7fg4myx88dvsndp80000gn/T/d20230623-6856-98pfen checkout --quiet 0

error: pathspec '0' did not match any file(s) known to git
```