Fix issue with UUID library in Jest
This fixes an issue related to the UUID library when running tests. Without this change, we get the following error:
```
/gutenberg-mobile/gutenberg/node_modules/uuid/dist/esm-browser/index.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export { default as v1 } from './v1.js';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      3 |  */
      4 | import fastDeepEqual from 'fast-deep-equal/es6';
    > 5 | import { v4 as uuid } from 'uuid';
        | ^
      6 |
      7 | /**
      8 |  * WordPress dependencies
```